In [6]:
#question 1
import numpy as np
abc_array = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(abc_array)


[0 1 2 3 4 5 6 7 8 9]


In [33]:
#question 2
import numpy as np
import random 
rand_matrix = np.random.randint(1, 9, (( 3,3)))
print(rand_matrix)


[[8 6 8]
 [4 6 7]
 [5 8 8]]


In [38]:
#question 3
import numpy as np
a_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b_array = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])
addition_result = a_array + b_array
print(addition_result)
subtraction_result = a_array - b_array
print(subtraction_result)
multiplication_result = a_array * b_array
print(multiplication_result)
division_result = np.where(b_array != 0, a_array / b_array, 0)
print("\nDivision Result:")
print(division_result)


[[10 10 10]
 [10 10 10]
 [10 10 10]]
[[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]
[[ 9 16 21]
 [24 25 24]
 [21 16  9]]

Division Result:
[[0.11111111 0.25       0.42857143]
 [0.66666667 1.         1.5       ]
 [2.33333333 4.         9.        ]]


In [51]:
#question 4
import numpy as np
abc_array = np.array([3, 6, 9, 11, 14, 17, 20, 23])
mean_value = np.mean(abc_array)
median_value = np.median(abc_array)
std_dev_value = np.std(abc_array)
print("Mean:", mean_value)
print("Median:", median_value)
print("Standard Deviation:", std_deviation_value)


Mean: 12.875
Median: 12.5
Standard Deviation: 6.469882147303767


In [44]:
#question 5
import numpy as np
my_array = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
even_indices = my_array[::2]
print(even_indices)


[0 2 4 6 8]


In [45]:
#question 6
import numpy as np
my_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
condition = my_array % 2 == 0 
filtered_array = my_array[condition]
print(filtered_array)


[2 4 6 8]


In [50]:
#question 7
import numpy as np
abc_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
reshaped_array = abc_array.reshape(2, 5)  
print("Original Array:")
print(abc_array)
print("\nReshaped Array:")
print(reshaped_array)


Original Array:
[ 1  2  3  4  5  6  7  8  9 10]

Reshaped Array:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [59]:
#question 8
import numpy as np
array1 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
array2 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
stack_horizontally = np.hstack((array1, array2))
stack_vertically = np.vstack((array1, array2))
print(stack_horizontally)
print(stack_vertically)


[ 0  1  2  3  4  5  6  7  8  9  1  2  3  4  5  6  7  8  9 10]
[[ 0  1  2  3  4  5  6  7  8  9]
 [ 1  2  3  4  5  6  7  8  9 10]]


In [60]:
#question 9
import numpy as np
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])
element_wise_result = array1 * array2
print("Element-wise Matrix Multiplication Result:")
print(element_wise_result)
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])
matrix_multiplication_result = np.dot(matrix1, matrix2)
print("\nTraditional Matrix Multiplication Result:")
print(matrix_multiplication_result)


Element-wise Matrix Multiplication Result:
[[ 5 12]
 [21 32]]

Traditional Matrix Multiplication Result:
[[19 22]
 [43 50]]


In [61]:
#Question 10
import numpy as np
max_value = np.max(array1)
min_value = np.min(array1)
max_index = np.argmax(array1)
min_index = np.argmin(array1)
print(max_value)
print(min_value)
print(max_index)
print(min_index)

4
1
3
0


In [63]:
#Q11
import numpy as np
matrix = np.random.randint(0,10,(3, 3))
sum_rows = np.sum(matrix, axis=1)
sum_columns = np.sum(matrix, axis=0)
print("Matrix:")
print(matrix)
print("sum of rows:")
print(sum_rows)
print("sum of columns:")
print(sum_columns)

Matrix:
[[6 2 5]
 [1 7 6]
 [4 6 6]]
sum of rows:
[13 14 16]
sum of columns:
[11 15 17]


In [74]:
#Q13
import numpy as np
temperature_data = np.array([
    [25.1, 26.2, 24.9, 25.5],
    [27.3, 26.8, 27.7, 28.0],
    [23.8, 24.5, 23.0, 24.1]
])

mean_temperature = np.mean(temperature_data)
std_deviation = np.std(temperature_data)
variance = np.var(temperature_data)
mean_temperature_by_location = np.mean(temperature_data, axis=1)
max_mean_location = np.argmax(mean_temperature_by_location)
min_mean_location = np.argmin(mean_temperature_by_location)
variance_by_year = np.var(temperature_data, axis=0)
year_with_highest_variance = np.argmax(variance_by_year)
print("1. Mean Temperature:", mean_temperature)
print("   Standard Deviation:", std_deviation)
print("   Variance:", variance)
print("2. Location with the Highest Average Temperature:", max_mean_location)
print("   Location with the Lowest Average Temperature:", min_mean_location)
print("3. Year with the Highest Temperature Variance:", year_with_highest_variance)

1. Mean Temperature: 25.575000000000003
   Standard Deviation: 1.5562374497485914
   Variance: 2.4218749999999996
2. Location with the Highest Average Temperature: 1
   Location with the Lowest Average Temperature: 2
3. Year with the Highest Temperature Variance: 2
